# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-29 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20160309_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailuser',
            name='document',
            field=models.FileField(default='doc/none/no-doc.pdf', upload_to='doc/'),
        ),
    ]
