# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-24 22:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identifiers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Door',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'That identifier name is already saved.'}, max_length=30, unique=True)),
                ('health', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('identifier_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identifiers.Identifier_types')),
            ],
        ),
    ]
