# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-04 16:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identifiers', '0001_initial'),
        ('doors', '0002_auto_20170204_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Controller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(error_messages={'unique': 'That identifier mac is already saved.'}, max_length=12, unique=True)),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('direction', models.BooleanField()),
                ('health', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('door', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doors.Door')),
                ('identifier_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identifiers.Identifier_types')),
            ],
        ),
    ]
